name: Build Conda Package

on: [ push, repository_dispatch ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Conda Build
        run: |
          conda install conda-build
      - name: Build conda
        run: |
          cd conda/
          conda build -c i4ds -c conda-forge .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          conda install anaconda-client
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/linux-64/pinocchio*.tar.bz2 --force
          
  install_and_test:
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda activate base
          conda install -c i4ds -c conda-forge pinocchio
          pinocchio
          pinocchio_rp
          